from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Activity)
admin.site.register(DiagnosedDisease)
admin.site.register(Diagnoses)
admin.site.register(DiagnosisRatings)
admin.site.register(DigitalDataRatings)
admin.site.register(Diseases)
admin.site.register(DomainExperts)
admin.site.register(ElectronicHealthRecords)
admin.site.register(KnowledgeEntries)
admin.site.register(Meetings)
admin.site.register(PatientDiseases)
admin.site.register(Patients)
admin.site.register(PatientSymptoms)
admin.site.register(Person)
admin.site.register(Practitioners)
admin.site.register(Prescription)
admin.site.register(Questions)
admin.site.register(SymptomDisease)
admin.site.register(Symptoms)
