# Generated by Django 5.0.4 on 2024-05-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontomed_app', '0003_alter_patients_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.BinaryField(null=True),
        ),
    ]
