# Generated by Django 5.0.4 on 2024-05-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontomed_app', '0004_alter_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='practitioner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ontomed_app.practitioners'),
            preserve_default=False,
        ),
    ]
