# Generated by Django 5.0.4 on 2024-05-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontomed_app', '0008_alter_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnoses',
            name='other_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
