# Generated by Django 5.0.4 on 2024-05-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontomed_app', '0010_alter_diagnoses_face_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioners',
            name='experience',
            field=models.CharField(max_length=100),
        ),
    ]
