# Generated by Django 5.0.4 on 2024-06-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontomed_app', '0011_alter_practitioners_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronichealthrecords',
            name='height',
        ),
        migrations.RemoveField(
            model_name='electronichealthrecords',
            name='weight',
        ),
        migrations.AddField(
            model_name='diagnoses',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='diagnoses',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
