# Generated by Django 5.0.4 on 2024-06-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontomed_app', '0013_remove_patientsymptoms_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnoses',
            name='regulatorrating',
            field=models.IntegerField(null=True),
        ),
    ]
